### ISSUE TITLE
Site fora do ar

### ISSUE THREAD

**Issue by tiago-rodrigues1** [Vinnh/social-media-profile#1]
Descrição:
Ao clicar no link do README, aparece a seguinte tela

![image](https://user-images.githubusercontent.com/70401246/184538241-231aaa8f-2fec-4047-8a72-352ecd53e8e5.png)

**Comment by Vinnh** [comment]
Alterei o link, tenta novamente, por favor!

**Comment by tiago-rodrigues1** [comment]
Funcionou 🚀
